[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_LS_VARIANT_PEREGRINO,NEXT_PUBLIC_LS_VARIANT_DISCIPULO,NEXT_PUBLIC_LS_VARIANT_CLARAVAL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
